baseURL = "https://makvaz.com"

theme = ["hugo-notice","jeffprod"]

# paginate = 5
# uglyurls = true

disableKinds = ["section"]

PygmentsCodeFences = true
PygmentsStyle = "monokai"

disqusShortname = "makvaz-com"

DefaultContentLanguage = "zametki"
copyright = "Everything is mine"

[languages]
[languages.notes]
  title = "Makvaz"
  baseURL = "https://notes.makvaz.com"
  weight = 4
  contentDir = "content/notes"
  [[languages.notes.menu.main]]
    url    = "/about/"
    name   = "About"
    weight = 2
    identifier = "about"
    pre = ""
  [[languages.notes.menu.main]]
    name = "Русская версия"
    weight = 1.1
    pre = "<i class='fas fa-rss-square fa-3x'>"
    url = "https://zametki.makvaz.com"
    identifier = "zametki.makvaz.com"
  [[languages.notes.menu.main]]
    name = "RSS"
    weight = 3
    pre = "<i class='fas fa-rss-square fa-3x'>"
    url = "/feed.xml"
    identifier = "RSS"
  [[languages.notes.menu.bottom]]
    name = "Privacy Policy"
    weight = 3
    url = "/privacy/"
    identifier = "privacy"
  [languages.notes.params]
    description = "Technical notes and other"
    googleAnalyticsCode = "UA-124592546-2"
    yandexMetrikaCode = "54471976"
[languages.zametki]
  title = "Макваз"
  weight = 2
  contentDir = "content/zametki"
  baseURL = "https://zametki.makvaz.com"
  [[languages.zametki.menu.main]]
    url    = "/about/"
    name   = "О сайте"
    weight = 2
    identifier = "about"
    pre = ""
  [[languages.zametki.menu.main]]
    name = "RSS"
    weight = 3
    pre = "<i class='fas fa-rss-square fa-3x'>"
    url = "/feed.xml"
    identifier = "RSS"
  [[languages.zametki.menu.main]]
    url    = "https://notes.makvaz.com"
    name   = "English version"
    weight = 2
    identifier = "notes.makvaz.com"
  [[languages.zametki.menu.bottom]]
    name = "Политика конфиденциальности"
    weight = 3
    url = "/privacy/"
    identifier = "privacy"

  [languages.zametki.params]
    description = "Технические заметки и не только"
    googleAnalyticsCode = "UA-111183533-1"
    yandexMetrikaCode = "54471931"
[languages.imhotnia]
  title = "IMHO-тня Макваз"
  weight = 2
  contentDir = "content/imhotnia"
  baseURL = "https://imhotnia.makvaz.com"
  [[languages.imhotnia.menu.main]]
    url    = "/about/"
    name   = "О сайте"
    weight = 2
    identifier = "about"
    pre = ""
  [[languages.imhotnia.menu.main]]
    name = "RSS"
    weight = 3
    pre = "<i class='fas fa-rss-square fa-3x'>"
    url = "/feed.xml"
    identifier = "RSS"
  [[languages.imhotnia.menu.bottom]]
    name = "Политика конфиденциальности"
    weight = 3
    url = "/privacy/"
    identifier = "privacy"

  [languages.zametki.params]
    description = "Про всё, кроме технического"
    googleAnalyticsCode = "UA-111183533-1"
    yandexMetrikaCode = "54471931"



enableRobotsTXT = true
rssLimit = 10
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"


[frontmatter]
date  = [":filename", ":default"]

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/page:slug"

[taxonomies]
    tag = "tags"
    archive = "archives"

[author]
    name = "Aliaksei Karneyeu"

[markup.goldmark.renderer]
unsafe= true

privacy_pack = true

[params]
  featureImg = "assets/img/header-pic.jpeg" 
  # description = "Технические заметки и не только"
