baseURL = "https://makvaz.com"
languageCode = "ru-ru"
title = "Makvaz"


theme = "jeffprod"

paginate = 5
# uglyurls = true

# disableKinds = ["section"]

PygmentsCodeFences = true
PygmentsStyle = "monokai"

disqusShortname = "makvaz-com"
googleAnalytics = "UA-111183533-1"

enableRobotsTXT = true
rssLimit = 10
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"


[frontmatter]
date  = [":filename", ":default"]

[permalinks]
    post = "/:year/:month/:day/:slug"
    page = "/page:slug"

[taxonomies]
    tag = "tags"
    archive = "archives"

[author]
    name = "Aliaksei Karneyeu"

sectionPagesMenu = "main"
[[menu.main]]
    name = "О сайте"
    weight = 2
    url = "/about/"
    identifier = "about"
    pre = ""
[[menu.main]]
    name = "RSS"
    weight = 3
    pre = "<i class='fas fa-rss-square fa-3x'>"
    url = "/feed.xml"
    identifier = "RSS"


[params]
  featureImg = "assets/img/header-pic.jpeg" 
  description = "Технические заметки и не только"
